#!/bin/bash

# bash functions to sync after logging into terminal
# use rsync to back up google drive files to my documents
# saves copy of files in three places (cloud, documents, separate hard drive)

backup(){
rsync -avz /cygdrive/c/users/Colin/Google_Drive /cygdrive/c/users/Colin/Documents/backup_google_drive

}


# directory change to windows environment
# change to document folder

cdd(){
				cd /cygdrive/c/users/Colin/Documents
}

# change to google doc folder

cdg(){
				cd /cygdrive/c/users/Colin/Google_Drive
}


# Use this function to compile into a pdf document containing notes
# Example: notes latex, notes vim

notes() {
# include if trying to exclude certain files
# list=$(find . -name '*.tex' \( ! -iname "begin.tex" \
# ! -iname "end.tex" \))
# find ~\(! -regex '.*/\..*' \)

NAME=notes_${1}
# exclude all directories starting with "."
# Thus, you cannot be in current directory to find
getPATH=$(find ~/documents -type d -name '.*' -prune -o -name "$NAME" -print)

cd $getPATH

# list=$(find . -name '*.tex' | sort) 
# use the above is searching for .tex files 
# pandoc ~/functions/latex/begin.tex $list ~/functions/latex/end.tex -o ${NAME}.pdf

list=$(find . -name '*.md' | sort)

# pandoc compiled output must be placed in same directory
pandoc $list -s -o ../${NAME}.pdf
chrome ../${NAME}.pdf
}
